version: '2'
services:
  factorio:
    build:
      context: .
      args:
        - VERSION=2.0.23
        - SHA256=e819fc9ad6df061bf9d4bffc91988dd18d0e3982c8b1c22c0525d78bda3ef216
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - /opt/factorio:/factorio
    environment:
      - TOKEN=f48d0c04eb7c67a7c4f22f1a305465
      - UPDATE_MODS_ON_START=true
